CREATE TABLE accounts (
	id BINARY(16) NOT NULL,
	customer_id BINARY(16) NOT NULL,
	account_type VARCHAR(10) NOT NULL,
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
);
